### ISSUE TITLE
Sugestão de atualização do CSS para o index.html

### ISSUE THREAD

**Issue by brunagil** [reprograma/reprograma-CV#48]
Uma sugestão para atualização do css no index.html da página de currículos, **visando melhor visualização e leitura e as cores mais acessíveis**

index.css 
.name {
    **/* background-color: #DDBCDC; */--** RETIRA ESSE CÓDIGO
    color: #7E459B;
    text-align: center;
    font-weight: bold;
    margin: 0.7rem 0;  --- AUMENTA O ESPAÇAMENTO 
    padding: 0.7rem; --- AUMENTA O ESPAÇAMENTO

**Comment by thayllachristine** [comment]
Outra sugestão:

Alterar o `margin-top` do `<h5>` que está logo abaixo do `<h3>` nas divs `work`, `study` e `interest`, pois o espaçamento está muito grande.

**Comment by kevindantas** [comment]
Teoricamente deveria ter pelo menos 4.5 no `contrast ratio` mas tinha 3.83

![image](https://user-images.githubusercontent.com/3884633/49343109-fd26ee80-f64a-11e8-9671-7d089d6d2cba.png)
